1.  **Security Overview**

| Term            | Definition                                                                                                                                                                                                                                                |
|-----------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Security        | The degree of protection against danger, damage, loss, and criminal activity. **Security is a constant balancing act between convenience and protection** **Mitigate risk and threats while also maintaining an acceptable level of ease of use.**        |
| Confidentiality | Confidentiality ensures that data is not disclosed to unintended persons.                                                                                                                                                                                 |
| Integrity       | Integrity ensures that data is not modified or tampered with.                                                                                                                                                                                             |
| Availability    | Availability ensures that a system is up so that data is available when needed.                                                                                                                                                                           |
| Non-Repudiation | Non-repudation provides the validation of a message's origin.                                                                                                                                                                                             |
| Asset           | Something that has value to an individual or an organization. is something that has value to an individual or an organization. You will mostly be dealing with virtual, i.e. data assets. Databases are a major example.                                  |
| Threat          | Anything that has the potential to cause the loss of an asset. Think **Risk**. Examples include: Trojans, Hackers, viruses, or an internal threat. These are **Blended Threats**. Look out for **ransomware**, **data exfiltration** in the future.       |
| Threat agent    | The person or entity that attempt or carries out a threat. Categories of a threat agent/actor: Internal vs external Resource and funding available Opportunistic? Class of threat agent: APT/competitor(spy) Employee Hacker                              |
| Vulnerability   | An opening—"a weakness in the system. This is known as a **vulnerability**.  The right person, such as an internal threat(disgruntled employee) with the correct know-how can use their elevated sever privileges, or attack through an enabled USB port. |
| Exploit         | An act, procedure, or piece of software that takes advantage of a vulnerability to carry out an attack.                                                                                                                                                   |

**1.1.3 Security Challenges**

| Challenge                        | Description                                                                                                                                                                                                                                                                                                                                                                                   |
|----------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Sophisticated Attacks            | Sophisticated attacks are complex, making them difficult to detect and thwart. Sophisticated attacks:  Use common internet tools and protocols, making it difficult to distinguish an attack from legitimate traffic. Vary their behavior, making the same attack appear differently each time.                                                                                               |
| Proliferation of Attack Software | A wide variety of attack tools are available on the internet, allowing anyone with a moderate level of technical knowledge to download the tools and run an attack.                                                                                                                                                                                                                           |
| Attack Scale and Velocity        | The scale and velocity of an attack can grow to millions of computers in a matter of minutes or days due to its ability to proliferate on the internet. Because modern attacks are not limited to user interactions, such as using a floppy disk, to spread an attack from machine to machine, the attacks often affect very large numbers of computers in a relatively short amount of time. |

**CIA**

| Term            | Description                                                                                                                                                                                                                 |
|-----------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Confidentiality | Confidentiality ensures that data is not disclosed to unintended persons. This is provided through *encryption*, which converts the data into a form that makes it less likely to be usable by an unintended recipient.     |
| Integrity       | Integrity ensures that data is not modified or tampered with. This is provided through *hashing*.                                                                                                                           |
| Availability    | Availability ensures the uptime of the system so that data is available when needed.                                                                                                                                        |
| Non-repudiation | Non-repudiation provides validation of a message's origin. For example, if a user sends a digitally signed email, they cannot claim later that the email was not sent. Non-repudiation is enforced by *digital signatures*. |

**Security Components**

| Component                | Description                                                                                                              |
|--------------------------|--------------------------------------------------------------------------------------------------------------------------|
| Physical Security        | Physical security includes all hardware and software necessary to secure data, such as firewalls and antivirus software. |
| Users and Administrators | Users and administrators are the people who use the software and the people who manage the software, respectively.       |
| Policies                 | Policies are the rules an organization implements to protect information.                                                |

**Risk management**

| Item             | Description                                                                                                                                                                                                                                                                                                                                                                                                                      |
|------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Risk Management  | Identifying security issues and deciding which countermeasures to take in reducing risk to an acceptable level.  reduce the risk for an organization to a level that is deemed acceptable by senior management.                                                                                                                                                                                                                  |
| Asset            | something that has value to the person or organization, such as sensitive information in a database.                                                                                                                                                                                                                                                                                                                             |
| Threat           | entity that can cause the loss of an asset or any potential danger to the confidentiality, integrity, or availability of information or systems, such as a data breach that results in a database being stolen.                                                                                                                                                                                                                  |
| Threat Agent     | an entity that can carry out a threat, such as a disgruntled employee who copies a database to a thumb drive and sells it to a competitor.                                                                                                                                                                                                                                                                                       |
| Vulnerability    | a weakness that allows a threat to be carried out, such as a USB port that is enabled on the server hosting the database or a server room door that is frequently left ajar. USB devices pose the greatest threat to the confidentiality of data in most secure organizations. There are so many devices that can support file storage that stealing data has become easy, and preventing it is difficult.                       |
| Exploit          | s a procedure or product that takes advantage of a vulnerability to carry out a threat, such as when a disgruntled employee waits for the server room door to be left ajar, copies the database to a thumb drive, and then sells it.                                                                                                                                                                                             |
| Countermeasure   | Countermeasures reduce the risk of a threat agent exploiting a vulnerability. An appropriate countermeasure: Provides a security solution to an identified problem. Is not dependent on secrecy. Is testable and verifiable. Provides uniform or consistent protection for all assets and users. Is independent of other safeguards. Requires minimal human intervention. Is tamper-proof. Has overrides and fail-safe defaults. |

**Threat Agents**

| Type     | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|----------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Employee | Employees = most dangerous threat agent: greatest access to information assets than any external attacker aka: **internal threats**. Employees can:  Get salty Get turned Get played Mess up company stuff. download malware, expose private info, and leave credentials where easily accessed. Can be phished, tricked by urgency or appeal to authority Must train to spot suspicious emails, attachments, websites and activity as part of onboarding. Must learn secure passwords( no writing) and clean desk. Train on organization’s security policy, spot internal and external threats. **Minimize the damage an employee can do to you or your job.** |
| Spy      | corporate espionage  New Guy is a spy! Probe network from outside for the other guy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Hacker   | Any threat agent who uses their technical knowledge to bypass security mechanisms to exploit a vulnerability to access information. Hacker subcategories:  *Script kiddies*, Copy and paste from internets, you if you don’t study. *Cybercriminals*, financial reward or revenge. *Cyber terrorists*, disrupting network-dependent institutions. *Hackitvist,* Mr Robot 2020.                                                                                                                                                                                                                                                                                 |

**1.2 Defense Planning**

| Term                   | Definition                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Layered security       | A security approach that combines multiple security controls and defenses to create a cumulative effect. For example, you can encrypt data on a hard drive. But that hard drive can also be inside a workstation that contains a host-based firewall and anti-malware software. And that workstation could be physically secured to a desk inside a locked office, which is inside a controlled-access building, which is surrounded by a fence. Layered security is a systematic approach to organizational security, identifies the best protection solution for each security layer, so if necessary, each layer can effectively stand on its own.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| Layered security model | A security approach that defines seven layers of security. **Policies/Procedures/Awareness:** user education, manageable network plans, employee onboarding and off-boarding, application development policies, third-party integration policies, general employment and user management policies **Physical:** fences, door locks, mantraps, turnstiles, device locks, server cages, cameras, motion detectors, and environmental controls. **Perimeter:** network's perimeter defense. DDOS/DNS attacks, Firewall configs, ACLs, wireless network security. **Network:** identify when an intrusion occurs. Install and configure switches and routers, implement VLANs, perform penetration testing, and utilize virtualization. **Host:** each individual workstation, laptop, and mobile device. The Host layer includes log management, OS hardening, patch management and implementation, auditing, and even malware and password attacks. **Application:** Applications. It also deals with how users access applications and resources. As such, it deals with authentication and authorization, user management, group policies, and even web application security **Data:** Store data properly, destroy data, and classify data. Cryptography and securing data transmissions. Attacks and Defenses. **Make EVERY obstacle count**. |
